from pathlib import Path
import hashlib,json,re,subprocess
r=Path('C:/ap/quiz_master');d=r/'.run/planet_release_20261011';m=json.loads((d/'package.json').read_text());stage=Path(m['stage'])
packet={'metadata':m,'scripts':{n:(stage/n).read_text() for n in ['cutover.sh','rehearse.py','backup_sqlite.py','Dockerfile']},'prepare_script':(d/'prepare.py').read_text(),'public_verifier':(d/'verify_public.py').read_text(),'evidence':{'final_web_build':'PASS110.1s, existing Cupertino font warning','source_preservation':'All131 source bytes compared exact; unchanged API SHA asserted','local_gates':'Previously4Python/fullGo+vet/114Flutter+analysisPASS','production':'Current130packs3998questions202articles;26feedbackOPEN; new pack not yet deployed','limits':'Remote fresh rehearsal/browser/physical Android not yet checked'}}
p=d/'review-packet.json';p.write_text(json.dumps(packet,ensure_ascii=False,indent=2));digest=hashlib.sha256(p.read_bytes()).hexdigest()
prompt='Independent read-only release safety review. No tools/MCP/shell/children/write/deploy. Inspect supplied exact Quiz Master packet. User authorizes deploy only after gates; review this preparation package, not claim rehearsal/browser passed. Check current-image/host/PVC guards, SQLite backup restore proof/row preservation, port collision/process cleanup, source/API preservation, staging normalization hiding revision defects, strict production binding verifier, immutable archive/checksums, prepare vs publish modes. Root already independently validated production URI question hashes and ten article refs. Respond ONLY JSON with verdict accept/revise, packet_sha256, findings, remaining_gates, limitations. Do not fabricate execution or source fetches. PACKET_SHA256 '+digest+'\n'+json.dumps(packet,ensure_ascii=False)
(d/'no-mcp.json').write_text('{"mcpServers":{}}')
result=subprocess.run(['claude','-p','--model','sonnet','--output-format','json','--tools','','--strict-mcp-config','--mcp-config',str(d/'no-mcp.json')],input=prompt,text=True,encoding='utf-8',stdout=subprocess.PIPE,stderr=subprocess.PIPE,cwd=r,timeout=240)
(d/'claude-static-runtime.json').write_text(result.stdout);assert result.returncode==0,result.stderr[-1000:]
raw=json.loads(result.stdout);v=json.loads(re.sub(r'^```(?:json)?\s*|\s*```$','',raw['result'].strip()));assert v['packet_sha256']==digest
(d/'claude-review.json').write_text(json.dumps(v,ensure_ascii=False,indent=2));print(json.dumps(v,ensure_ascii=False,indent=2))
