from pathlib import Path
import hashlib,json,re,subprocess
r=Path('C:/ap/quiz_master');d=r/'.run/planet_release_20261011'
packet={'original_review':json.loads((d/'claude-review.json').read_text()),'corrections':{n:(d/n).read_text() for n in ['strict_rehearsal.py','rehearse-strict.py','staging-revisions.go.txt','prepare_remote.py','verify_public.py','test_verifier.py']},'actual_proofs':{n:(d/n).read_text() for n in ['strict-rehearsal.txt','remote-prepare.txt']},'root_evidence':{'backend_diff':'git diff317b339..d228c9e next/server only catalog_test.go/collection_test.go; strict script enforces all suffix_test.go','browser':'Final packagedWeb390x844 actually viewed; 131/4008library, Study menu navigation, no consoleerrors. New pack play/article only proven API rehearsal; published-browser gate pending. No physicalAndroid claim','port':'DEPLOY.lock held for prepare and strict rehearsal; root uses no concurrent staging workers. Probe releases port, not a reservation; process exits/readiness timeout catches a collision. This limit remains explicit.','bundle_cache':'131 new directory-dependent revisions added; original231 retained,362after; strict131growth assertionPASS','verifier':'Native caught expected count shadowing, fixed expected_questions; mocked85bindings PASS (not liveverification)','scope':'Re-review pre-cutover gates. Release/public post-cutover verification remains required; do not pretend publication completed'}}
p=d/'followup-packet.json';p.write_text(json.dumps(packet,ensure_ascii=False,indent=2));sha=hashlib.sha256(p.read_bytes()).hexdigest()
prompt='Independent fresh read-only review of corrections to the supplied actual Claude release review. Previous resumed attempt timed out after180s; that was no approval or rejection. No tools/MCP/shell/files/children/publish. Check supplied corrections and actual observed evidence against F1-F6. Strict supplementary rehearsal on a second fresh backup explicitly checks all30 independently recomputed staging revisions BEFORE original normalization,131cachegrowth,and priorAPIguest/history reads. Original immutable archive remains unchanged; supplemental checks are required external release gates, not changes secretly inserted into archive. Host lock serializes our own runs; residualport TOCTOU documented, noqueueclaimed. Transfer exactSHA verified beforeunpack per newlysuppliedprepare_remote. Backend tests onlysource delta is asserted. Answer ONLYJSON verdict accept/revise for these pre-cutovergates, packet_sha256, findings, remaining_gates,limitations. Actual postpublication/browsernewpack checks remainpending; nophysicalAndroidrequirement for content-onlyWebrelease. PACKET_SHA256 '+sha+'\n'+json.dumps(packet,ensure_ascii=False)
res=subprocess.run(['claude','-p','--model','sonnet','--effort','medium','--output-format','json','--tools','','--strict-mcp-config','--mcp-config',str(d/'no-mcp.json')],input=prompt,text=True,encoding='utf-8',stdout=subprocess.PIPE,stderr=subprocess.PIPE,cwd=r,timeout=240)
(d/'claude-followup-runtime.json').write_text(res.stdout);assert res.returncode==0,res.stderr[-1000:]
raw=json.loads(res.stdout);v=json.loads(re.sub(r'^```(?:json)?\s*|\s*```$','',raw['result'].strip()));assert v['packet_sha256']==sha
(d/'claude-followup.json').write_text(json.dumps(v,ensure_ascii=False,indent=2));print(json.dumps(v,ensure_ascii=False,indent=2))
