import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mockito/mockito.dart';
import 'package:quiz_master/core/api/api_client.dart';
import 'package:quiz_master/features/auth/domain/repositories/auth_repository_interface.dart';
import 'package:quiz_master/features/quiz/domain/repositories/quiz_repository.dart';

/// Helper to create a ProviderContainer with overrides for testing
ProviderContainer createTestContainer({
  List<Object>? overrides,
}) {
  return ProviderContainer(
    overrides: overrides?.cast() ?? const [],
  );
}

/// Helper to wrap a widget in ProviderScope
Widget createTestWidget({
  required Widget widget,
  List<Object>? overrides,
}) {
  return ProviderScope(
    overrides: overrides?.cast() ?? const [],
    child: widget,
  );
}

/// Mock providers for testing
class MockProviders {
  static ApiClient mockApiClient() => MockApiClient();
  static QuizRepository mockQuizRepository() => MockQuizRepository();
  static AuthRepositoryInterface mockAuthRepository() => MockAuthRepository();
}

/// Base mock classes (will be generated by mockito)
class MockApiClient extends Mock implements ApiClient {}
class MockQuizRepository extends Mock implements QuizRepository {}
class MockAuthRepository extends Mock implements AuthRepositoryInterface {}
