import { ThemeConfig } from '../types';

export const holidayTheme: ThemeConfig = {
    name: 'Новый год',
    background: '../../assets/home-alone-bg.jpg',
    confetti: ['#800020', '#FFBF00', '#FFFFF0'],
    styles: {
        page: "bg-cover bg-center bg-no-repeat transition-all duration-500",
        overlay: "bg-black/10 backdrop-blur-[1px]",
        heading: "text-slate-900 tracking-tight font-black",
        subtext: "text-slate-600",
        text: "text-slate-800",
        sidebar: "bg-white/90 backdrop-blur-md border-r border-slate-200 rounded-r-3xl md:rounded-3xl",
        sidebarHeader: "pt-4",
        sidebarScrollbar: "scrollbar-thin scrollbar-thumb-slate-200",
        item: "w-full rounded-lg border-t-0 border-l-4 border-transparent transition-all duration-300",
        itemActive: "bg-amber-100 text-amber-900 border-amber-500 shadow-sm scale-105",
        itemCorrect: "bg-emerald-50 text-emerald-700 border-emerald-500",
        itemIncorrect: "bg-rose-50 text-rose-700 border-rose-500",
        itemUnanswered: "text-slate-600 hover:bg-slate-50",
        itemIcon: "bg-white shadow-sm rounded-full",
        card: "bg-ivory-50 text-slate-900 border border-slate-200 shadow-xl backdrop-blur-sm",
        cardWrapper: "",
        cardImage: "brightness-100",
        cardHeader: "border-b border-slate-100 bg-white/50 p-3 md:p-4",
        cardTitle: "text-slate-900 tracking-tight font-bold",
        progressBar: "bg-slate-200",
        progressFill: "bg-red-700 shadow-sm",
        pill: "bg-white border-slate-200 text-slate-600",
        pillActive: "text-amber-600",
        pillCorrect: "bg-emerald-50 border-emerald-200 text-emerald-700",
        pillIncorrect: "bg-rose-50 border-rose-200 text-rose-700",
        pillNeutral: "bg-slate-50 border-slate-200 text-slate-900",
        option: "bg-white border border-slate-200 hover:bg-slate-50 hover:border-amber-500/50 text-slate-800 p-3",
        optionSelected: "border-amber-500 bg-amber-50 text-amber-900 z-10",
        optionCorrect: "border-emerald-500 bg-emerald-50 text-emerald-700",
        optionIncorrect: "border-rose-500 bg-rose-50 text-rose-700",
        optionIcon: "w-6 h-6 rounded-full border border-slate-200 text-slate-400 bg-transparent text-xs",
        explanation: "bg-amber-50/50 border border-amber-200 text-slate-700",
        btnShuffle: "bg-white text-slate-800 border-slate-200 hover:bg-slate-50",
        btnReset: "bg-white text-slate-800 border-slate-200 hover:bg-slate-50",
        btnSecondary: "bg-white text-slate-800 border-slate-200 hover:bg-slate-50",
        folderCard: "bg-white/80 backdrop-blur-sm border border-slate-200 hover:border-amber-500/50",
        folderIcon: "bg-amber-50 text-amber-600",
        folderText: "text-slate-900",
        quizCard: "bg-white/80 backdrop-blur-sm border border-slate-200 hover:border-amber-500/50",
    }
};
