export const romanceTheme = {
    name: 'Романтика',
    background: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=2000&auto=format&fit=crop',
    confetti: ['#f43f5e', '#fb7185', '#ffffff'],
    styles: {
        page: "bg-cover bg-center bg-no-repeat transition-all duration-500",
        overlay: "bg-rose-100/20 backdrop-blur-[1px]",
        heading: "text-rose-900 font-serif italic font-medium",
        subtext: "text-rose-300",
        text: "text-rose-800",
        sidebar: "bg-white/60 backdrop-blur-xl border-none rounded-r-[3rem] md:rounded-[3rem]",
        sidebarHeader: "pt-4",
        sidebarScrollbar: "scrollbar-thin scrollbar-thumb-rose-100",
        item: "w-full rounded-2xl transition-all duration-300 mb-2 p-3",
        itemActive: "bg-rose-500 text-white shadow-xl shadow-rose-200 scale-105",
        itemCorrect: "bg-emerald-500 text-white",
        itemIncorrect: "bg-rose-600 text-white",
        itemUnanswered: "bg-rose-50/50 text-rose-400 hover:bg-rose-50 hover:text-rose-600",
        itemIcon: "bg-rose-200/50 text-rose-600",
        card: "bg-white/90 text-rose-900 border border-rose-100 shadow-2xl rounded-[3rem] backdrop-blur-md",
        cardWrapper: "shadow-rose-100/50",
        cardImage: "brightness-105 saturate-105",
        cardHeader: "p-4 md:p-6 pb-2 text-center",
        cardTitle: "text-rose-900 font-serif italic font-medium text-xl",
        progressBar: "bg-rose-50",
        progressFill: "bg-rose-500",
        pill: "bg-rose-50 text-rose-500 border-rose-100",
        pillActive: "text-rose-600 font-bold",
        pillCorrect: "bg-emerald-50 text-emerald-600 border-emerald-100",
        pillIncorrect: "bg-rose-50 text-rose-600 border-rose-100",
        pillNeutral: "bg-rose-50 text-rose-400",
        option: "bg-rose-50/30 border border-rose-50 hover:border-rose-300 text-rose-700 p-3 rounded-2xl text-center",
        optionSelected: "bg-white border-rose-400 text-rose-900 shadow-sm",
        optionCorrect: "bg-emerald-50 border-emerald-400 text-emerald-700",
        optionIncorrect: "bg-rose-50 border-rose-400 text-rose-700 opacity-60",
        optionIcon: "hidden",
        explanation: "bg-rose-50 border-rose-100 text-rose-900 rounded-2xl italic text-center",
        btnShuffle: "bg-white text-rose-500 hover:bg-rose-50 border border-rose-100",
        btnReset: "bg-rose-500 text-white hover:bg-rose-600 border-none",
        btnSecondary: "bg-rose-50 text-rose-500 border-rose-100 hover:bg-rose-100",
        folderCard: "bg-white/90 backdrop-blur-md border-rose-50 rounded-3xl shadow-lg",
        folderIcon: "bg-rose-100 text-rose-500",
        folderText: "text-rose-900 font-medium italic",
        quizCard: "bg-white/90 backdrop-blur-md border-rose-50 rounded-3xl shadow-lg",
    }
};
