export const summerTheme = {
    name: 'Лето',
    background: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2000&auto=format&fit=crop',
    confetti: ['#facc15', '#fb923c', '#ffffff'],
    styles: {
        page: "bg-cover bg-center bg-no-repeat transition-all duration-500",
        overlay: "bg-sky-400/20 backdrop-blur-none",
        heading: "text-slate-900 font-black",
        subtext: "text-slate-500",
        text: "text-slate-800",
        sidebar: "bg-white/80 backdrop-blur-md border-none rounded-r-[3rem] md:rounded-[3rem] shadow-xl",
        sidebarHeader: "pt-4",
        sidebarScrollbar: "scrollbar-thin scrollbar-thumb-sky-100",
        item: "w-full rounded-xl transition-all duration-300 mb-2 p-3",
        itemActive: "bg-orange-500 text-white shadow-lg shadow-orange-500/30 scale-105",
        itemCorrect: "bg-green-500 text-white",
        itemIncorrect: "bg-red-500 text-white",
        itemUnanswered: "bg-sky-50 text-sky-700 hover:bg-sky-100",
        itemIcon: "bg-black/5 rounded-full",
        card: "bg-white text-slate-900 border-none shadow-2xl rounded-[2.5rem]",
        cardWrapper: "drop-shadow-2xl",
        cardImage: "contrast-110 brightness-105",
        cardHeader: "p-4 md:p-6 pb-2",
        cardTitle: "text-slate-900 font-black text-xl",
        progressBar: "bg-sky-100",
        progressFill: "bg-orange-500",
        pill: "bg-sky-50 text-sky-600 border-sky-100",
        pillActive: "text-orange-500",
        pillCorrect: "bg-green-100 text-green-700",
        pillIncorrect: "bg-red-100 text-red-700",
        pillNeutral: "bg-sky-50 text-sky-600",
        option: "bg-sky-50/50 border-2 border-transparent hover:border-orange-300 hover:bg-sky-50 text-slate-700 p-4 rounded-2xl",
        optionSelected: "border-orange-500 bg-white shadow-md text-slate-900",
        optionCorrect: "border-green-500 bg-green-50 text-green-700",
        optionIncorrect: "border-red-500 bg-red-50 text-red-700",
        optionIcon: "w-8 h-8 rounded-full bg-sky-100 text-sky-600 font-bold",
        explanation: "bg-orange-50 border-none text-orange-950 rounded-2xl",
        btnShuffle: "bg-sky-100 text-sky-600 hover:bg-sky-200 border-none",
        btnReset: "bg-orange-100 text-orange-600 hover:bg-orange-200 border-none",
        btnSecondary: "bg-sky-50 text-sky-600 hover:bg-sky-100 border-none",
        folderCard: "bg-white/80 backdrop-blur-md border-none rounded-3xl shadow-lg hover:shadow-xl",
        folderIcon: "bg-sky-100 text-sky-500",
        folderText: "text-slate-800 font-bold",
        quizCard: "bg-white/80 backdrop-blur-md border-none rounded-3xl shadow-lg hover:shadow-xl",
    }
};
