// Mocks generated by Mockito 5.4.6 from annotations
// in quiz_master/test/features/quiz/data/repositories/quiz_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:quiz_master/core/api/api_client.dart' as _i2;
import 'package:quiz_master/features/auth/domain/entities/auth_entities.dart'
    as _i6;
import 'package:quiz_master/features/quiz/domain/entities/quiz_entities.dart'
    as _i4;
import 'package:quiz_master/features/statistics/domain/entities/statistics_entities.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Quiz>> getAllQuizzes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQuizzes, []),
            returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
          )
          as _i3.Future<List<_i4.Quiz>>);

  @override
  _i3.Future<List<_i4.Quiz>> getAdminQuizzes(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminQuizzes, [token]),
            returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
          )
          as _i3.Future<List<_i4.Quiz>>);

  @override
  _i3.Future<_i4.Quiz> getQuizById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizById, [id]),
            returnValue: _i3.Future<_i4.Quiz>.value(
              _i5.dummyValue<_i4.Quiz>(
                this,
                Invocation.method(#getQuizById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Quiz>);

  @override
  _i3.Future<_i4.Quiz> getQuizSummary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizSummary, [id]),
            returnValue: _i3.Future<_i4.Quiz>.value(
              _i5.dummyValue<_i4.Quiz>(
                this,
                Invocation.method(#getQuizSummary, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Quiz>);

  @override
  _i3.Future<_i4.Question> getQuestion(String? quizId, String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestion, [quizId, questionId]),
            returnValue: _i3.Future<_i4.Question>.value(
              _i5.dummyValue<_i4.Question>(
                this,
                Invocation.method(#getQuestion, [quizId, questionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Question>);

  @override
  _i3.Future<_i4.Feedback> checkAnswer(
    String? quizId,
    String? questionId,
    int? answerIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAnswer, [quizId, questionId, answerIndex]),
            returnValue: _i3.Future<_i4.Feedback>.value(
              _i5.dummyValue<_i4.Feedback>(
                this,
                Invocation.method(#checkAnswer, [
                  quizId,
                  questionId,
                  answerIndex,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Feedback>);

  @override
  _i3.Future<bool> submitScore(
    String? quizId,
    int? score,
    int? total,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitScore, [quizId, score, total, token]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> reportIssue(
    String? quizId,
    String? questionId,
    String? message,
    String? questionText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportIssue, [
              quizId,
              questionId,
              message,
              questionText,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i6.AuthResponse> login(_i6.AuthRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i3.Future<_i6.AuthResponse>.value(
              _i5.dummyValue<_i6.AuthResponse>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i3.Future<_i6.AuthResponse>);

  @override
  _i3.Future<_i6.AuthResponse> register(_i6.AuthRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i3.Future<_i6.AuthResponse>.value(
              _i5.dummyValue<_i6.AuthResponse>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i3.Future<_i6.AuthResponse>);

  @override
  _i3.Future<_i6.AuthResponse> guestLogin(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#guestLogin, [username]),
            returnValue: _i3.Future<_i6.AuthResponse>.value(
              _i5.dummyValue<_i6.AuthResponse>(
                this,
                Invocation.method(#guestLogin, [username]),
              ),
            ),
          )
          as _i3.Future<_i6.AuthResponse>);

  @override
  _i3.Future<_i6.AuthResponse> refresh(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [refreshToken]),
            returnValue: _i3.Future<_i6.AuthResponse>.value(
              _i5.dummyValue<_i6.AuthResponse>(
                this,
                Invocation.method(#refresh, [refreshToken]),
              ),
            ),
          )
          as _i3.Future<_i6.AuthResponse>);

  @override
  _i3.Future<List<_i7.LeaderboardEntry>> getLeaderboard({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i7.LeaderboardEntry>>.value(
              <_i7.LeaderboardEntry>[],
            ),
          )
          as _i3.Future<List<_i7.LeaderboardEntry>>);

  @override
  _i3.Future<List<_i7.LeaderboardEntry>> getAdminLeaderboard(
    String? token, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminLeaderboard, [token], {#limit: limit}),
            returnValue: _i3.Future<List<_i7.LeaderboardEntry>>.value(
              <_i7.LeaderboardEntry>[],
            ),
          )
          as _i3.Future<List<_i7.LeaderboardEntry>>);

  @override
  _i3.Future<_i6.UserQuota?> getUserQuota(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getUserQuota, [token]),
            returnValue: _i3.Future<_i6.UserQuota?>.value(),
          )
          as _i3.Future<_i6.UserQuota?>);
}
