// Mocks generated by Mockito 5.4.6 from annotations
// in quiz_master/test/features/home/presentation/providers/home_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:quiz_master/features/quiz/domain/entities/quiz_entities.dart'
    as _i4;
import 'package:quiz_master/features/quiz/domain/repositories/quiz_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [QuizRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRepository extends _i1.Mock implements _i2.QuizRepository {
  MockQuizRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Quiz>> getAllQuizzes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQuizzes, []),
            returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
          )
          as _i3.Future<List<_i4.Quiz>>);

  @override
  _i3.Future<_i4.Quiz> getQuizById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizById, [id]),
            returnValue: _i3.Future<_i4.Quiz>.value(
              _i5.dummyValue<_i4.Quiz>(
                this,
                Invocation.method(#getQuizById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Quiz>);

  @override
  _i3.Future<_i4.Quiz> getQuizSummary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizSummary, [id]),
            returnValue: _i3.Future<_i4.Quiz>.value(
              _i5.dummyValue<_i4.Quiz>(
                this,
                Invocation.method(#getQuizSummary, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Quiz>);

  @override
  _i3.Future<_i4.Question> getQuestion(String? quizId, String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestion, [quizId, questionId]),
            returnValue: _i3.Future<_i4.Question>.value(
              _i5.dummyValue<_i4.Question>(
                this,
                Invocation.method(#getQuestion, [quizId, questionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Question>);

  @override
  _i3.Future<_i4.Feedback> checkAnswer(
    String? quizId,
    String? questionId,
    int? answerIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAnswer, [quizId, questionId, answerIndex]),
            returnValue: _i3.Future<_i4.Feedback>.value(
              _i5.dummyValue<_i4.Feedback>(
                this,
                Invocation.method(#checkAnswer, [
                  quizId,
                  questionId,
                  answerIndex,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Feedback>);

  @override
  _i3.Future<bool> submitScore(
    String? quizId,
    int? score,
    int? total,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitScore, [quizId, score, total, token]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> reportIssue(
    String? quizId,
    String? questionId,
    String? message,
    String? questionText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportIssue, [
              quizId,
              questionId,
              message,
              questionText,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
